### ISSUE TITLE
Silk screen labels for C35 and L12 are swapped

### ISSUE THREAD

**Issue by NKelias** [Nitrokey/nitrokey-lora-hardware#1]
The labels for C35 and L12 on the silk screen layer are swapped w.r.t their actual positions

![Screenshot_20190716_113349](https://user-images.githubusercontent.com/36131955/61283546-9ad7c400-a7bd-11e9-8506-9c0aa393ceb0.png)

**Comment by jans23** [comment]
Fixed with commit 156eeae.
